# Generated by Django 3.2.4 on 2021-06-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesteBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
