# Generated by Django 3.2.4 on 2021-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesteBackend', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='TesteBackend.Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='TesteBackend.Categoria'),
        ),
    ]
